=== beaudin/bremo/src/bremoswing/ressource/String.dtd
<?xml encoding="UTF-8"?>

<!ELEMENT language (JLABELS,JBUTTONS,STRINGS)>
<!ATTLIST language
    id ID #REQUIRED>

<!ELEMENT JLABELS (jlabel*)>

<!ELEMENT JBUTTONS (jbutton*)>

<!ELEMENT STRINGS (string*)>

<!ELEMENT jlabel (#PCDATA)>
<!ATTLIST jlabel
   id ID #REQUIRED>

<!ELEMENT jbutton (#PCDATA)>
<!ATTLIST jbutton
    id ID #REQUIRED>

<!ELEMENT string (#PCDATA)>
<!ATTLIST string
    id ID #REQUIRED>

=== beaudin/bremo/branches/Bremo 2_DE/src/bremoswing/ressource/String_en.xml
?xml version = "1.0" encoding="UTF-8" standalone="no" ?>
<!DOCTYPE language SYSTEM "String.dtd">

<language id = "EN" >
  <JLABELS>
    <jlabel id = "1">label1</jlabel>
	<jlabel id = "2">label2</jlabel>
	<jlabel id = "3">label3</jlabel>
  </JLABELS>

  <JBUTTONS>
    <jbutton id = "1">button1</jbutton>
	<jbutton id = "2">button2</jbutton>
	<jbutton id = "3">button3 </jbutton>
  </JBUTTONS>

  <STRINGS>
    <string id = "1">string1</string>
	<string id = "2">string2</string>
	<string id = "3">string3</string>
  </STRINGS>
</language>

=== beaudin/bremo/branches/Bremo 2_DE/src/bremoswing/ressource/String_de.xml
<?xml version = "1.0" encoding="UTF-8" standalone="no" ?>
<!DOCTYPE language SYSTEM "String.dtd">

<language id = "DE" >
  <JLABELS>
    <jlabel id = "swingbremo_label_1"> Berechnung gestartet </jlabel>
	<jlabel id = "swingbremo_label_2"> Initialisierung l채uft ... </jlabel>
	<jlabel id = "swingbremo_label_3"> Operation gestartet .... </jlabel> 
	<jlabel id = "swingbremo_label_4"> Bitte InputFile Neu Ausw채hlen ! </jlabel>
	<jlabel id = "swingbremo_label_5"> Datei Werden geladen ... </jlabel>
	<jlabel id = "swingbremo_label_6"> Datei mit Erfolg Importiert ! </jlabel>
	<jlabel id = "swingbremo_label_7"> Import von Datei Unterbrechen ! </jlabel>
	<jlabel id = "swingbremo_label_8"> Fehler aufgetreten ! </jlabel>
	<jlabel id = "swingbremo_label_9"> Operationen beendet. </jlabel>
	<jlabel id = "swingbremo_label_10"> Berechnung Fertig ! </jlabel>
	<jlabel id = "swingbremo_label_11"> Verlustteilung wird berechnet... </jlabel>
	<jlabel id = "swingbremo_label_12"> Externe Datei mit Erfolg Importiert ! </jlabel>
	<jlabel id = "swingbremo">  </jlabel>
  </JLABELS>

  <JBUTTONS>
    <jbutton id = "swingbremo_ToolTip_play"> Berechnung ausf체hren </jbutton>
	<jbutton id = "swingbremo_ToolTip_choose"> InputFile ausw채hlen </jbutton>
	<jbutton id = "swingbremo_ToolTip_stop"> Stop Bremo </jbutton>
	<jbutton id = "swingbremo_ToolTip_see"> Schauen Sie Ergebniss als Graphik </jbutton>
	<jbutton id = "swingbremo_ToolTip_doc">Erzeugen/Editieren InputFile </jbutton>
	<jbutton id = "3">button3 </jbutton>
  </JBUTTONS>

  <STRINGS>
    <string id = "1">string1</string>
	<string id = "2">string2</string>
	<string id = "3">string3</string>
  </STRINGS>
</language>

=== beaudin/bremo/branches/Bremo 2_DE/src/bremoswing/ressource/String_fr.xml
<?xml version = "1.0" encoding="UTF-8" standalone="no" ?>
<!DOCTYPE language SYSTEM "String.dtd">

<language id = "FR" >
  <JLABELS>
    <jlabel id = "swingbremo_label_1"> Demarage des Calcules </jlabel>
	<jlabel id = "swingbremo_label_2"> Initialisation en Cours ... </jlabel>
	<jlabel id = "swingbremo_label_3"> Demarage des Operationen.... </jlabel> 
	<jlabel id = "swingbremo_label_4"> Choisir de nouveau le fichier d´entré ! </jlabel>
	<jlabel id = "swingbremo_label_5"> Chargement du Fichier en Cours ... </jlabel>
	<jlabel id = "swingbremo_label_6"> Fichier importé avec succes ! </jlabel>
	<jlabel id = "swingbremo_label_7"> Importation du fichier interrompue ! </jlabel>
	<jlabel id = "swingbremo_label_8"> une Erreur est Survenue ! </jlabel>
	<jlabel id = "swingbremo_label_9"> Fin des Operations </jlabel>
	<jlabel id = "swingbremo_label_10"> Fin des Calculs </jlabel>
	<jlabel id = "swingbremo_label_11"> Calcul de Perte en cours... </jlabel>
	<jlabel id = "swingbremo_label_12"> Fichier externe importé avec succes ! </jlabel>
	<jlabel id = "swingbremo">  </jlabel>
  </JLABELS>

  <JBUTTONS>
    <jbutton id = "swingbremo_ToolTip_play"> Demarer Bremo </jbutton>
	<jbutton id = "swingbremo_ToolTip_choose"> Choisir fichier d´entré </jbutton>
	<jbutton id = "swingbremo_ToolTip_stop"> Stoper Bremo </jbutton>
	<jbutton id = "swingbremo_ToolTip_see"> Regarder les Resultats sous forme Graphique </jbutton>
	<jbutton id = "swingbremo_ToolTip_doc"> Creer / Editer Fichier d´entré </jbutton>
	<jbutton id = "3">button3 </jbutton>
  </JBUTTONS>

  <STRINGS>
    <string id = "1">string1</string>
	<string id = "2">string2</string>
	<string id = "3">string3</string>
  </STRINGS>
</language>
